export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const LIST_ROUTE = '/list'
export const MEDICINE_ROUTE = '/medicine'
